spring:
  datasource:
    url: jdbc:postgresql://192.168.0.126/botbuilder
    username: botuser
    password: botpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
logging:
  file.name: ./log/bot-builder.log
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
    org.springframework.security: INFO
    org.springframework.web.HttpLogging: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
bots:
  testbot:
     username: my_test_builder_bot
     token: 8176452782:AAF2x4x9X6540wsosYeR6yQwwsCCewW2_5c
     enabled: false
  angeimebel:
     username: angeimebel_bot
     token: 7720206806:AAGEidLmH6d4zf2s0-iI_rOs8IP71gR3I0A
     enabled: true
